name: Publish Docker image
on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"

jobs:
  publish_image:
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: 'Get Previous tag'
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            natsuwumi/these-waifus-also-dont-exist:latest
            natsuwumi/these-waifus-also-dont-exist:${{ steps.previoustag.outputs.tag }}
          labels: ${{ steps.docker_meta.outputs.labels }}
