name: Update Docker Hub description
on:
  push:
    branches:
      - master
    paths:
      - README.md
      - .github/workflows/update_description.yml

jobs:
  update_description:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: natsuwumi/these-waifus-also-dont-exist
